specVersion: 0.2.0
name: parallel-crowdloan-subql
version: 1.0.0
description: ''
repository: 'https://github.com/parallel-finance/parallel-crowdloan-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x883d421a9e9da134efbd88d1c5b8387880bbb4e3226e589587e5c577ddb7f9a5'
  endpoint: 'wss://staging-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloans
