specVersion: 0.2.0
name: parallel-crowdloan-subql
version: 1.0.0
description: ''
repository: 'https://github.com/parallel-finance/parallel-crowdloan-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xd3799a78c35fb11ef09ad18e2de227f5f6d4a0521a45235058375c9eea6c673f'
  endpoint: 'wss://regnet2-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloans
